export type AdminReviewsContentProps = {
  loading: boolean;
  busyId: string | null;
  tab: "pending" | "approved";
  setTab: (tab: "pending" | "approved") => void;
  pendingCount: number;
  approvedCount: number;
  onRefresh: () => Promise<void> | void;
  newPendingCount: number;
  stats: {
    total: number;
    pending: number;
    approved: number;
    averageRating: number;
  };
  search: string;
  setSearch: (value: string) => void;
  ratingFilter: number | "all";
  setRatingFilter: (value: number | "all") => void;
  sortMode: "newest" | "rating_desc" | "rating_asc";
  setSortMode: (value: "newest" | "rating_desc" | "rating_asc") => void;
  totalFiltered: number;
  selectedCount: number;
  onSelectAllVisible: () => void;
  onClearSelection: () => void;
  onBulkApprove: () => Promise<void>;
  onBulkMoveToPending: () => Promise<void>;
  onBulkDelete: () => Promise<void>;
  onExportCsv: () => void;
  selectedIds: string[];
  reviews: any[];
  onToggleSelected: (id: string) => void;
  onApprove: (id: string) => void;
  onMoveToPending: (id: string) => void;
  onReject: (id: string) => void;
  page: number;
  setPage: (page: number) => void;
  totalPages: number;
};